base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('contato/', views.contato, name='contato'),
    path('examples/', views.example_view, name='example_view')
]

rest_api/urls.py
from django.urls import path

from rest_framework.routers import SimpleRouter

from rest_api.views import hello_world, ReservaModelViewSet, PetshopModelViewSet

app_name = 'rest_api'

router = SimpleRouter(trailing_slash=True)
router.register('reserva', ReservaModelViewSet)
router.register('petshop', PetshopModelViewSet)

## /api/reserva

urlpatterns = [
    path('hello', hello_world, name='hello_world_api')
]

urlpatterns += router.urls

ultima/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('base.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('rest_api.urls', namespace='api'))
]

base/models.py
from django.db import models


# Create your models here.
class ExampleModel(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Formulário de Exemplo'
        ordering = ['name']


class ContatoModel(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    mensagem = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False, verbose_name='Lido', blank=True)

    def __str__(self):
        return f'{self.pk} {self.nome} [{self.email}]'

    class Meta:
        verbose_name = 'Forlumário de Contato'
        ordering = ['-created_at']


class Petshop(models.Model):
    nome = models.CharField(verbose_name='Nome', max_length=100)
    rua = models.CharField(verbose_name='Rua', max_length=100)
    numero = models.CharField(verbose_name='Número', max_length=100)
    bairro = models.CharField(verbose_name='Bairro', max_length=50)

    def qtd_reservas(self):
        return self.reservas.count()


class ReservaModel(models.Model):
    TAMANHO_OPCOES = (
        (0, 'Pequeno'),
        (1, 'Médio'),
        (2, 'Grande')
    )
    TURNO_OPCOES = (
        ('manha', 'Manhã'),
        ('tarde', 'Tarde')
    )
    nome = models.CharField(max_length=50, verbose_name='Nome')
    email = models.EmailField(verbose_name='E-mail')
    nome_pet = models.CharField(max_length=50, verbose_name='Nome do Pet')
    data = models.DateField(verbose_name='Data', help_text='dd/mm/yyyy')
    turno = models.CharField(verbose_name='Turno', max_length=10, choices=TURNO_OPCOES)
    tamanho = models.IntegerField(verbose_name='Tamanho', choices=TAMANHO_OPCOES)
    obs = models.TextField(blank=True)
    petshop = models.ForeignKey('Petshop', related_name='reservas',
                                on_delete=models.CASCADE,
                                blank=True,
                                null=True)

    def __str__(self):
        return f'Tutor {self.nome}: {self.data} - {self.turno} para {self.nome_pet}'

    class Meta:
        verbose_name = 'Reserva de Banho'
        verbose_name_plural = 'Reservas de Banho'

rest_api/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms

from base.models import ContatoModel


class ContatoForm(forms.ModelForm):
    class Meta:
        model = ContatoModel
        fields = ['nome', 'email', 'mensagem']

base/views.py
from django.shortcuts import render

from base.forms import ContatoForm
from base.models import ExampleModel, ContatoModel


def inicio(request):
    return render(request, template_name='inicio.html')


def contato(request):
    sucesso = False
    if request.method == 'GET':
        form = ContatoForm()
    else:
        form = ContatoForm(request.POST)
        if form.is_valid():
            sucesso = True
            form.save()
    contexto = {
        'nome': 'Maria',
        'telefone': '(99) 99999-9999',
        'form': form,
        'sucesso': sucesso
    }
    return render(request, 'contato.html', contexto)


# Create your views here.
def example_view(request):
    examples = ExampleModel.objects.all()
    return render(request,
                  template_name='example_template.html',
                  context={'examples': examples})

rest_api/views.py
from django.shortcuts import render
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly

from base.models import ReservaModel, Petshop
from rest_framework import viewsets

from rest_framework.response import Response
from rest_framework.decorators import api_view

from rest_api.serializers import ReservaModelSerializer, PetshopNestedSerializer


# Create your views here.
@api_view(['GET', 'POST'])
def hello_world(request):
    if request.method == 'POST':
        return Response({'message': f'Hello World {request.data["nome"]}'})

    return Response({'message': 'Hello World GET endpoint'})


class ReservaModelViewSet(viewsets.ModelViewSet):
    queryset = ReservaModel.objects.all()
    serializer_class = ReservaModelSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticatedOrReadOnly]


class PetshopModelViewSet(viewsets.ModelViewSet):
    queryset = Petshop.objects.all()
    serializer_class = PetshopNestedSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticatedOrReadOnly]

base/templates/contato.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Pet Online</title>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="col-lg-8 mx-auto p-3 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                    <span class="fs-4">Pet online</span>
                </a>
            </header>
            <main>
                <h1>Fale Conosco</h1>
                <h5>
                    Em caso de dúvidas entre em contato com {{ nome }} pelo telefone {{ telefone }}
                </h5>
                {% if sucesso %}
                <p class="alert alert-success">Mensagem enviada com sucesso!</p>
                {% endif %}
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="id_nome">Nome</label>
                                <input type="text" id="id_nome" class="form-control" name="nome">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="id_email">Email</label>
                                <input type="email" id="id_email" class="form-control" name="email">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="id_mensagem">Mensagem</label>
                                <textarea name="mensagem" id="id_mensagem" class="form-control" cols="30" rows="10"></textarea>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <button type="submit" class="btn btn-primary">Enviar mensagem</button>
                </form>
            </main>
            <footer class="pt-5 my-5 text-muted border-top">
                Curso python utlima school
            </footer>
        </div>
        <script src="/static/js/bootstrap.bundle.js"></script>
    </body>
</html>

base/templates/example_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Minha Página</title>
</head>
<body>
    <h1>My Examples</h1>
    <ul>
        {% for exemplo in examples %}
            <li>{{ exemplo.name }}</li>
        {% endfor %}
    </ul>
</body>
</html>

base/templates/inicio.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Pet Online</title>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="col-lg-8 mx-auto p-3 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                    <span class="fs-4">Pet online</span>
                </a>
            </header>
            <main>
                <h1>Reserve já o banho do seu pet</h1>
            </main>
            <footer class="pt-5 my-5 text-muted border-top">
                Curso python utlima school
            </footer>
        </div>
        <script src="/static/js/bootstrap.bundle.js"></script>
    </body>
</html>